name: build test & deploy springboot 

on:
    #push:
      #branches: 
        - main
    pull_request:
      branches: 
        - main
  
    workflow_dispatch:

jobs:
    build:
        name: build and test springboot
        runs-on: ubuntu-latest
        steps:
            - name: checkout - clone repo into runner
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: 'temurin'
                cache: maven
            - name: Unit Tests
              run: mvn -B test --file pom.xml
        
            - name: Build the application
              run: |
                mvn clean
                mvn -B package --file pom.xml


