name: build test & deploy springboot 

on:
    push:
      branches: 
        - main
    pull_request:
      branches: 
        - main
  
    workflow_dispatch:

jobs:
    build:
        name: build springboot
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: 17


